### PR TITLE
Bump compat for MLJModelnterface

### LINKED ISSUE #31: Issue when precompiling with package version >=0.3.0
Hello,

Thank for your work to support XGBoost on Julia so far!
I have noticed a bug with the latest versions, with MLJXGBoostInterface v0.3.0 and higher (XGBoost v2.2.1). MLJXGBoostInterface fails to precompile, with the following error:

```
Failed to precompile MLJXGBoostInterface [54119dfa-1dab-4055-a167-80440f4f7a91] to C:\Users\XXXX\.julia\compiled\v1.8\MLJXGBoostInterface\jl_B69.tmp.
ERROR: LoadError: UndefVarError: feature_importances not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ C:\Users\XXXX\.julia\packages\MLJXGBoostInterface\ZLP7C\src\MLJXGBoostInterface.jl:117
 [3] include
   @ .\Base.jl:419 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1554
 [5] top-level scope
   @ stdin:1
```

Retrograding to MLJXGBoostInterface v0.2.1 (which downgrade the XGBoost version to v1.5.2) is solving the issue.

### PR DESCRIPTION
**Pull request by ablaom**
To close #31.

### CODE REVIEW

**Comment by ExpandingMan** [comment]
Yeah, it's easy to let old versions get out of sync.  Probably best practice to remove them and always keep a single version on the list.  It might be inevitable that'll piss someone off, but it's probably for the best since nobody is ever going to check that some patch or new feature doesn't break some obscure API function of some old version of a package that nobody uses anymore.

**Comment by ExpandingMan** [comment]
Please trigger registrator.  Thanks!

**Comment by ablaom** [comment]
Thanks for the review @ExpandingMan 

> Yeah, it's easy to let old versions get out of sync. Probably best practice to remove them and always keep a single version on the list. 

I could yank the offending versions from General.jl. Is that what your suggesting?

**Comment by ExpandingMan** [comment]
> I could yank the offending versions from General.jl. Is that what your suggesting?

No, no, nothing so extreme.  Just that it's probably not very good practice to have `compat` entries that allow multiple versions of a package between which there are breaking changes.  More of a comment about sem-ver in general than specific to this.  There are no other `compat` entries in this package like this so nothing to be done here.

**Pull request merged**
