### PR TITLE
Add generic interface tests from MLJTestIntegration

### PR DESCRIPTION
**Pull request by ablaom**

### CODE REVIEW

**Comment by ablaom** [comment]
@ExpandingMan

**Comment by ExpandingMan** [comment]
Thanks, I'll add these in my PR because that'll just be easier.

**Comment by ablaom** [comment]
Marking as draft as #21 to incorporate.

**Comment by ExpandingMan** [comment]
Yeah, sorry, I was distracted by my XGBoost.jl PR.  I will return my attention to this when that is done.

**Comment by ExpandingMan** [comment]
I'm very stumped as to what's going on here... it seems to be complaining that it is getting the wrong `num_class` argument which apparently defaults to `1`.  Part of the problem here is that with current XGBoost.jl it tries to return a completely wrong array for classification in which it cuts off the multi-dimensional output.  My guess is that this was never working properly but in the binary case it didn't matter because the second output didn't matter because it had to satisfy $1 - p_{1}$.  This is all going to have to get changed anyway if my PR gets merged because I'm outputting proper array sizes whereas the old version seems to be improperly flattening the arrays.

So if you don't mind I think I'd prefer to see if my PR to XGBoost.jl has a chance of being merged sometime soon before picking up the pieces of whatever happened here.

**Comment by ablaom** [comment]
Yes, as I recall, the existing XBoost.jl flattens the output of probability arrays and special cases binary probabilities (only one instead of two, per observation). This required some logic to sort out, and it is quite possible your refactor has broken this.

**Comment by ablaom** [comment]
Close as added in another merged PR

**Pull request closed without merging**
