### PR TITLE
Exposed early stopping rounds to MLJ including incorporating to defau…

### PR DESCRIPTION
**Pull request by wilan-wong-1**
…lt to optimal ntree_limit during predict(). Added relevant tests.

### CODE REVIEW

**Comment by ablaom** [comment]
@wilan-wong-1 Would you mind adding  a codecov.yml file, like [here](https://github.com/JuliaAI/CategoricalDistributions.jl/blob/dev/.github/codecov.yml) to stop the codecov fussiness?

**Comment by ablaom** [comment]
@ExpandingMan Any chance you could review. I've not really been following this particular issue.

**Comment by wilan-wong-1** [comment]
Hi @ExpandingMan, any updates on this? Thanks!

**Comment by ExpandingMan** [comment]
Sorry, clearly I missed the first ping somehow.

It's been quite a while since I've used the MLJ interface, so to be honest I don't feel super capable of contemplating those aspects of it at the moment.

Feel like I should just merge this...

**Pull request merged**
