### PR TITLE
Add nthread arg to XGBoostRegressor , XGBoostCount and XGBoostClassifier

### PR DESCRIPTION
**Pull request by dmahasen**
Hi, I have added nthread arg to XGBoostRegressor , XGBoostCount and XGBoostClassifier. So, number of threads used can be limited.

### CODE REVIEW

**Review by ablaom — APPROVED** [review]
@dmahasen Thanks for this contribution!

Looks good to me and will merge now.

However, I wasn't actually able to notice a speed-up with the number of threads on my machine.  What have your observations been?

```julia
julia> mach.model.nthread
12

julia> @time fit!(mach, force=true, verbosity=-1)
  3.513411 seconds (104.47 k allocations: 6.427 MiB, 0.27% gc time)
Machine{XGBoostClassifier,…} @287 trained 7 times; caches data
  args: 
    1:  Source @985 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @642 ⏎ `AbstractVector{Multiclass{3}}`


julia> mach.model.nthread = 1
1

julia> @time fit!(mach, force=true, verbosity=-1)
  3.522144 seconds (104.47 k allocations: 6.427 MiB)
Machine{XGBoostClassifier,…} @287 trained 8 times; caches data
  args: 
    1:  Source @985 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @642 ⏎ `AbstractVector{Multiclass{3}}`
```

**Comment by dmahasen** [comment]
@ablaom,  It is my pleasure to make this tiny contribution. 

I have experienced a time difference when I change the number of threads. 

Here, X has 1000 observations with 100 values for each. 

julia> m_xgb_theta1_2 = machine(xgb_theta1_2, X, y)
Machine{XGBoostRegressor,…} @323 trained 0 times; caches data
  args: 
    1:  Source @880 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @407 ⏎ `AbstractVector{Continuous}`


julia> @time fit!(m_xgb_theta1_2,verbosity=-1 )
  1.977043 seconds (39.83 k allocations: 4.895 MiB)
Machine{XGBoostRegressor,…} @323 trained 1 time; caches data
  args: 
    1:  Source @880 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @407 ⏎ `AbstractVector{Continuous}` 

The main requirement I had was to limit the number of cores in fitting the model. Otherwise, it consumes all the cores on my machine.



> @dmahasen Thanks for this contribution!
> 
> Looks good to me and will merge now.
> 
> However, I wasn't actually able to notice a speed-up with the number of threads on my machine. What have your observations been?
> 
> ```julia
> julia> mach.model.nthread
> 12
> 
> julia> @time fit!(mach, force=true, verbosity=-1)
>   3.513411 seconds (104.47 k allocations: 6.427 MiB, 0.27% gc time)
> Machine{XGBoostClassifier,…} @287 trained 7 times; caches data
>   args: 
>     1:  Source @985 ⏎ `Table{AbstractVector{Continuous}}`
>     2:  Source @642 ⏎ `AbstractVector{Multiclass{3}}`
> 
> 
> julia> mach.model.nthread = 1
> 1
> 
> julia> @time fit!(mach, force=true, verbosity=-1)
>   3.522144 seconds (104.47 k allocations: 6.427 MiB)
> Machine{XGBoostClassifier,…} @287 trained 8 times; caches data
>   args: 
>     1:  Source @985 ⏎ `Table{AbstractVector{Continuous}}`
>     2:  Source @642 ⏎ `AbstractVector{Multiclass{3}}`
> ```

**Comment by dmahasen** [comment]
@ablaom,  It is my pleasure to make this tiny contribution. 

I have experienced a time difference when I change the number of threads. 

Here, X has 1000 observations with 100 values for each. 

`julia> xgb_thread_2 = xgbReg(num_round=1000,nthread= 2);`

`julia> m_xgb_thread_2 = machine(xgb_thread_2, X, y);`

`julia> @time fit!(m_xgb_thread_2,verbosity=-1 );`
  2.038276 seconds (39.83 k allocations: 4.895 MiB)

`julia> xgb_thread_6 = xgbReg(num_round=1000,nthread= 6);`

`julia> m_xgb_thread_6 = machine(xgb_thread_6, X, y);`

`julia> @time fit!(m_xgb_thread_6,verbosity=-1 );`
  0.881676 seconds (39.83 k allocations: 4.895 MiB)


The main requirement I had was to limit the number of cores in fitting the model. Otherwise, it consumes all the cores on my machine.

**Comment by ablaom** [comment]
Ah, yes of course! In tree methods the parallelism occurs across features not observations! I had a lot of observations but few features in my test.

Thanks again!

**Pull request merged**
