### PR TITLE
support MLJ training per data sample weight

### LINKED ISSUE #55: missing access `weight=` in DMatrix for sample weight
in Python, this is called `sample_weight` https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.XGBRegressor.fit

looks like XGBoost.jl exposes it via: https://github.com/dmlc/XGBoost.jl/blob/08c38da58050ca2df29f0e5fdcc06ce21de1dcd8/src/dmatrix.jl#L56

Do we have access to this concept in this package?

### PR DESCRIPTION
**Pull request by Moelf**
fix #55

### CODE REVIEW

**Comment by ablaom** [comment]
Looks good to me, thank you. 

Could we at least have a smoke test verifying addition of weights makes a difference?

**Comment by Moelf** [comment]
done!

**Review by ablaom — APPROVED** [review]
Thanks @Moelf  for you valuable contribution 🙏🏾

**Comment by Moelf** [comment]
let's try the CI again

**Pull request merged**
